In [7]:
import pandas as pd

# links we want to examine
linkids = [128255,169017,182993,181188,121161,120676,182544,167734,148462,204266,167761,203126]

In [8]:
'''linkids = [5535,   7146,  14813,  17204,  28580,  28721,  32377,  35889,
        40861,  42551,  47763,  60034,  61897,  62457,  62532,  62539,
        63799,  64201,  64290,  64826,  64838,  64839,  64857,  64858,
        64863,  65152,  65365,  65436,  65768,  66666,  68155,  68880,
        73141,  73200,  73630,  74723,  74724,  74727,  75017,  75785,
        76403,  76786,  77597,  79714,  79868,  79895,  80067,  80077,
        80246,  80633,  81094,  81841,  82411,  86618,  88033,  89423,
        94457,  94570,  94840,  94855,  94924,  94939,  94976,  95039,
        95051,  95052,  95151,  95631,  96143,  96323,  96444,  96896,
        97345,  97573,  97798,  98299,  98825, 100543, 100577, 100756,
       101211, 101692, 101726, 102423, 102469, 107534, 107808, 108113,
       108258, 108776, 108798, 108840, 108936, 109031, 109062, 109063,
       109085, 109124, 109251, 109267, 109303, 109307, 109427, 109525,
       110302, 110821, 111015, 111223, 111336, 111537, 111578, 111923,
       111977, 112461, 112474, 112586, 112602, 113092, 113148, 113397,
       113639, 113925, 113961, 114000, 114089, 114135, 114214, 114379,
       114441, 114447, 114485, 114491, 114526, 114538, 114542, 114564,
       114622, 114625, 114729, 114772, 114803, 114812, 115162, 115268,
       115610, 115794, 115809, 115815, 115833, 115844, 115856, 115860,
       116102, 116220, 116345, 116457, 116580, 116727, 117100, 117116,
       117159, 117169, 117186, 117300, 117315, 117318, 117322, 117342,
       117344, 117370, 117372, 117397, 117546, 117653, 117680, 117708,
       117874, 118168, 118210, 118335, 118482, 118489, 118573, 118908,
       118956, 118981, 119261, 119350, 119503, 119650, 120635, 120929,
       121102, 121240, 122259, 122564, 123372, 124371, 124613, 125015,
       125165, 125299, 125319, 125551, 125578, 125596, 125597, 125603,
       125619, 125870, 126256, 126487, 127152, 127958, 128582, 128990,
       129163, 129213, 129263, 129284, 129492, 129494, 129887, 130329,
       130341, 130358, 130381, 130426, 130881, 131439, 131537, 132680,
       135290, 137668, 139472, 141704, 142236, 142981, 142996, 144563,
       144572, 144586, 144970, 145035, 145122, 145244, 145282, 145579,
       146600, 146626, 146654, 146666, 147029, 147109, 147204, 147264,
       147286, 147287, 147332, 147661, 147779, 147968, 147991, 148001,
       148057, 148076, 148354, 148589, 148643, 148859, 148921, 148947,
       148987, 149095, 149296, 149324, 149356, 149376, 149963, 150013,
       150027, 150148, 150216, 150699, 150872, 150903, 151434, 151736,
       151846, 152434, 152955, 153254, 153407, 153536, 153866, 154260,
       154589, 154606, 155014, 155261, 155762, 155881, 156107, 157100,
       157101, 157172, 157200, 157282, 157317, 157562, 157637, 157742,
       157834, 157862, 158125, 158396, 158439, 158530, 158658, 158690,
       158697, 158710, 158767, 158849, 158895, 159512, 159572, 159763,
       160668, 160678, 161028, 161463, 161481, 161561, 161597, 161615,
       161684, 161867, 161904, 161953, 162171, 162371, 162758, 162887,
       162894, 162899, 162908, 162924, 163740, 163765, 163783, 163797,
       163812, 164367, 164771, 167027, 167045, 167125, 167214, 167263,
       167275, 167380, 167851, 167921, 168006, 168081, 168198, 168216,
       168233, 168275, 168333, 168336, 168388, 168393, 168638, 168645,
       168649, 168659, 168687, 168700, 168733, 168738, 168863, 168908,
       168913, 168921, 168980, 169025, 169150, 169151, 169757, 169767,
       169790, 169817, 169975, 170063, 170154, 170474, 170488, 170522,
       170528, 170619, 170847, 171012, 171725, 172008, 172009, 172021,
       172032, 172048, 172068, 172080, 172099, 172581, 172701, 172728,
       173261, 173450, 173695, 173781, 173800, 173999, 174311, 174398,
       174697, 174767, 174994, 175181, 175211, 175876, 176186, 176647,
       176948, 177498, 177927, 177950, 178367, 178403, 179300, 181238,
       181873, 181890, 181965, 181982, 182086, 182172, 182542, 184302,
       184365, 184470, 184845, 185393, 185409, 185412, 185790, 186826,
       186846, 186860, 188173, 188174, 189491, 191354, 191949, 192221,
       192331, 192337, 192734, 192944, 193312, 193506, 193678, 193730,
       193769, 193773, 193810, 193819, 193883, 193919, 193921, 193988,
       193995, 194050, 194052, 194338, 194471, 194472, 194516, 194520,
       194645, 194718, 194829, 194930, 194946, 194966, 194986, 195002,
       195020, 195051, 195073, 195085, 195106, 195115, 195135, 195150,
       195190, 195196, 195213, 195239, 195264, 195306, 195311, 195315,
       195342, 195378, 195396, 195442, 195488, 195510, 195536, 195574,
       195675, 195711, 196732, 196794, 196812, 197061, 197112, 197144,
       197170, 197184, 197249, 197264, 197359, 197387, 198186, 198188,
       198262, 198269, 198274, 198281, 198518, 198520, 199202, 199249,
       199250, 199623, 199627, 199641, 199717, 201524, 202717, 202887,
       203072, 203233, 203270, 203330, 203525, 203676, 203790, 203814,
       203945, 204148, 204692, 204737, 204778, 204842, 204973, 204987,
       205046, 205057, 205081, 205083, 205100, 205125, 205126, 205142,
       205180, 205275, 205310, 205326, 205363, 205378, 205403, 205421,
       205498, 205508, 205546, 205608, 205628, 205660, 205760, 205859,
       205926, 205976, 206324, 206780, 207071, 207203, 207297, 207363,
       207382, 207653, 207677, 207698, 207726, 207738, 207766, 207780,
       207807, 207831, 207893, 207902, 207999, 208063, 208086, 208226,
       208392, 208617, 208696, 209218, 209396, 209434, 209505, 209697,
       209701, 209710, 209849, 209892, 209923, 209974, 209990, 214948,
       223169, 230920, 232917, 232986, 233854, 236590, 240248, 241822,
       242683, 243175, 243343, 244487, 244752, 246034, 246045, 246128,
       246423, 246460, 246472, 246480, 246525, 246693, 246700, 246713,
       246963, 248531, 248903, 254795, 256583, 256685, 258561] '''

In [ ]:
# loop over linkids to import data from 12 transposed matrices and write data to 12 output csvs

for n in range(0, len(linkids)):
    with open('data1_2_T.csv') as file, open('targets_output'+ str(n+1)+'.csv', 'w') as out_f:
        for i, line in enumerate(file):
                if i == linkids[n]:
                    out_f.write(line)
                    break
    with open('data3_4_T.csv') as file, open('targets_output'+ str(n+1) +'.csv', 'a') as out_f:
        for i, line in enumerate(file):
                if i == linkids[n]:
                    out_f.write(line)
                    break

    with open('data5_6_T.csv') as file, open('targets_output'+ str(n+1) +'.csv', 'a') as out_f:
        for i, line in enumerate(file):
                if i == linkids[n]:
                    out_f.write(line)
                    break

    with open('data7_8_T.csv') as file, open('targets_output'+ str(n+1) +'.csv', 'a') as out_f:
        for i, line in enumerate(file):
                if i == linkids[n]:
                    out_f.write(line)
                    break

    with open('data9_10_T.csv') as file, open('targets_output'+ str(n+1) +'.csv', 'a') as out_f:
        for i, line in enumerate(file):
                if i == linkids[n]:
                    out_f.write(line)
                    break

    with open('data11_12_T.csv') as file, open('targets_output'+ str(n+1) +'.csv', 'a') as out_f:
        for i, line in enumerate(file):
                if i == linkids[n]:
                    out_f.write(line)
                    break

In [ ]:
# concentate different rows for each linkid and concentate 12 linkids to targets.csv
df = pd.read_csv('targets_output1.csv', header = None)
df = pd.DataFrame(df.values.reshape(1, -1)) 
for n in range(1, len(linkids)):
    df1 = pd.read_csv('targets_output'+ str(n+1) +'.csv', header = None)
    df = df.append(pd.DataFrame(df1.values.reshape(1, -1)))
df.to_csv('targets.csv', header= None)

In [4]:
# import targets.csv and drop first column - get 12 rows * 8760 columns
targets = pd.read_csv('targets.csv', header = None)
targets = targets.drop(targets.columns[0], axis = 1)

In [5]:
targets[:].fillna(0, inplace=True)